/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class edu_wpi_first_math_WPIMathJNI */

#ifndef _Included_edu_wpi_first_math_WPIMathJNI
#define _Included_edu_wpi_first_math_WPIMathJNI

#include "../../../../../../AppData/Local/Android/Sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wpi_first_math_WPIMathJNI
 * Method:    discreteAlgebraicRiccatiEquation
 * Signature: ([D[D[D[DII[D)V
 */
extern "C" JNIEXPORT void JNICALL Java_edu_wpi_first_math_WPIMathJNI_discreteAlgebraicRiccatiEquation
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jdoubleArray);

/*
 * Class:     edu_wpi_first_math_WPIMathJNI
 * Method:    exp
 * Signature: ([DI[D)V
 */
extern "C" JNIEXPORT void JNICALL Java_edu_wpi_first_math_WPIMathJNI_exp
  (JNIEnv *, jclass, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     edu_wpi_first_math_WPIMathJNI
 * Method:    pow
 * Signature: ([DID[D)V
 */
extern "C" JNIEXPORT void JNICALL Java_edu_wpi_first_math_WPIMathJNI_pow
  (JNIEnv *, jclass, jdoubleArray, jint, jdouble, jdoubleArray);

/*
 * Class:     edu_wpi_first_math_WPIMathJNI
 * Method:    isStabilizable
 * Signature: (II[D[D)Z
 */
extern "C" JNIEXPORT jboolean JNICALL Java_edu_wpi_first_math_WPIMathJNI_isStabilizable
  (JNIEnv *, jclass, jint, jint, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
